# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.SmallIntegerField(choices=[(1, 'boy'), (2, 'girl')], default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Image/')),
                ('grade', models.IntegerField(blank=True, max_length=5, null=True)),
                ('college', models.SmallIntegerField(choices=[(1, 'SDCS'), (2, 'SMIE'), (3, 'ABCD')], default=1)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('realname', models.CharField(blank=True, max_length=20, null=True)),
                ('IDnum', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
