# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='college',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
