# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_auto_20170522_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('introduction', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='名字')),
                ('establish_date', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('introduction', models.CharField(default='', max_length=100, verbose_name='简介')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Image/')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Control.Community'),
        ),
    ]
