# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0004_account_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptor', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Control.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('author', models.ManyToManyField(related_name='publish_notice', to='Control.Account')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Control.Community')),
            ],
        ),
    ]
