# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0005_inform_notice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inform',
            new_name='Message',
        ),
    ]
