# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0006_auto_20170522_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Community_Message',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='Private_Message',
        ),
    ]
