# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0007_auto_20170522_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='community_message',
            name='author',
            field=models.ManyToManyField(related_name='publish_notice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='private_message',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
