# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0008_auto_20170522_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='社团名字'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='社团缩写'),
        ),
    ]
