# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0009_auto_20170524_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='community',
        ),
        migrations.AddField(
            model_name='activity',
            name='community',
            field=models.ManyToManyField(to='Control.Community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='简介'),
        ),
    ]
