# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0010_auto_20170524_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='community',
        ),
        migrations.AddField(
            model_name='activity',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control.Community'),
        ),
    ]
