# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0011_auto_20170524_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='community',
        ),
        migrations.AddField(
            model_name='activity',
            name='community',
            field=models.ManyToManyField(related_name='community_activity', to='Control.Community'),
        ),
    ]
