# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0013_auto_20170524_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名字'),
        ),
    ]
