# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0017_auto_20170524_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '普通'), (2, '通知')], default=1),
        ),
    ]
