# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0018_blog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_community',
            options={'ordering': ['community']},
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.AlterField(
            model_name='account_community',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='account_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
