# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0020_twit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
