# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0021_auto_20170525_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twit',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='twit',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
