# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0022_auto_20170525_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value0', models.CharField(blank=True, max_length=20, null=True)),
                ('value1', models.CharField(blank=True, max_length=20, null=True)),
                ('value2', models.CharField(blank=True, max_length=20, null=True)),
                ('value13', models.CharField(blank=True, max_length=20, null=True)),
                ('value14', models.CharField(blank=True, max_length=20, null=True)),
                ('value15', models.CharField(blank=True, max_length=20, null=True)),
                ('value16', models.CharField(blank=True, max_length=20, null=True)),
                ('value17', models.CharField(blank=True, max_length=20, null=True)),
                ('value18', models.CharField(blank=True, max_length=20, null=True)),
                ('value19', models.CharField(blank=True, max_length=20, null=True)),
                ('value20', models.CharField(blank=True, max_length=20, null=True)),
                ('value21', models.CharField(blank=True, max_length=20, null=True)),
                ('value22', models.CharField(blank=True, max_length=20, null=True)),
                ('value23', models.CharField(blank=True, max_length=20, null=True)),
                ('value24', models.CharField(blank=True, max_length=20, null=True)),
                ('value25', models.CharField(blank=True, max_length=20, null=True)),
                ('value26', models.CharField(blank=True, max_length=20, null=True)),
                ('value27', models.CharField(blank=True, max_length=20, null=True)),
                ('value28', models.CharField(blank=True, max_length=20, null=True)),
                ('value29', models.CharField(blank=True, max_length=20, null=True)),
                ('value30', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MT_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataType', models.CharField(default='char', max_length=20)),
                ('nmae', models.CharField(max_length=20, null=True)),
                ('field_Num', models.IntegerField()),
                ('Tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.Community')),
            ],
        ),
        migrations.CreateModel(
            name='MT_Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('Tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.Community')),
            ],
        ),
        migrations.AddField(
            model_name='mt_fields',
            name='table_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.MT_Tables'),
        ),
        migrations.AddField(
            model_name='mt_data',
            name='Table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.MT_Tables'),
        ),
        migrations.AddField(
            model_name='mt_data',
            name='Tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.Community'),
        ),
    ]
