# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0023_auto_20170525_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_fields',
            name='dataType',
            field=models.SmallIntegerField(choices=[(1, 'char'), (2, 'int'), (3, 'bool')], default=1, max_length=20),
        ),
    ]
