# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0024_auto_20170525_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt_fields',
            old_name='nmae',
            new_name='name',
        ),
    ]
